### ISSUE TITLE
Can't load a game page

### ISSUE THREAD

**Issue by LiamDawe** [flavioislima/HeroicGamesLauncher#38]
Any time I go to view a game page in the app, it gives me this:

> Error occurred in handler for 'getGameInfo': Error: Cannot find module './secrets'
> Require stack:
> - /tmp/.mount_heroiccEGV2J/resources/app.asar/build/main.js
> - 
>     at Module._resolveFilename (internal/modules/cjs/loader.js:972:15)
>     at Function.n._resolveFilename (electron/js2c/browser_init.js:249:921)
>     at Module._load (internal/modules/cjs/loader.js:848:27)
>     at Function.f._load (electron/js2c/asar_bundle.js:5:12738)
>     at Module.require (internal/modules/cjs/loader.js:1032:19)
>     at require (internal/modules/cjs/helpers.js:72:18)
>     at /tmp/.mount_heroiccEGV2J/resources/app.asar/build/main.js:109:24
>     at electron/js2c/browser_init.js:189:579
>     at Object.<anonymous> (electron/js2c/browser_init.js:157:9268)
>     at Object.emit (events.js:315:20) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [
>     '/tmp/.mount_heroiccEGV2J/resources/app.asar/build/main.js',
>     undefined
>   ]
> }

This is with the latest version.

Interestingly, it does work fine in the previous 1.0.1 release so something you changed between them broke it. This is on Arch.

**Comment by flavioislima** [comment]
That's bad, I'm uploading a fix.

**Comment by flavioislima** [comment]
Check now: https://github.com/flavioislima/HeroicGamesLauncher/releases/tag/v1.0.3

**Comment by LiamDawe** [comment]
Looks good, fixed.
